/**
 * Automated Database Setup Script for INSEC System
 * Creates the database, executes schema.sql, and seeds test data (Admin, Editor, 15+ Incident Records).
 */

const path = require('path');
const serverNodeModules = path.join(__dirname, '../server/node_modules');
const mysql = require(path.join(serverNodeModules, 'mysql2/promise'));
const bcrypt = require(path.join(serverNodeModules, 'bcryptjs'));
const fs = require('fs');
require(path.join(serverNodeModules, 'dotenv')).config({ path: path.join(__dirname, '../server/.env') });

const DB_HOST = process.env.DB_HOST || '127.0.0.1';
const DB_PORT = parseInt(process.env.DB_PORT || '3306', 10);
const DB_USER = process.env.DB_USER || 'root';
const DB_PASSWORD = process.env.DB_PASSWORD || '';
const DB_NAME = process.env.DB_NAME || 'insec_data';

async function setupDatabase() {
  console.log(`Connecting to MySQL on ${DB_HOST}:${DB_PORT} as ${DB_USER}...`);
  
  // Step 1: Connect to server without database
  const connection = await mysql.createConnection({
    host: DB_HOST,
    port: DB_PORT,
    user: DB_USER,
    password: DB_PASSWORD,
    multipleStatements: true,
  });

  try {
    console.log(`Creating database '${DB_NAME}' if not exists...`);
    await connection.query(
      `CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`
    );
    await connection.query(`USE \`${DB_NAME}\`;`);

    // Step 2: Read and execute schema.sql
    console.log('Executing database/schema.sql...');
    const schemaSql = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8');
    await connection.query(schemaSql);
    console.log('Schema tables created successfully.');

    // Step 3: Seed Users
    const adminPasswordHash = await bcrypt.hash('Admin@12345', 10);
    const editorPasswordHash = await bcrypt.hash('Editor@12345', 10);

    await connection.query(`
      INSERT INTO users (name, email, password_hash, role, is_active)
      VALUES 
        ('केन्द्रीय प्रशासक (Admin)', 'admin@insec.org.np', ?, 'admin', TRUE),
        ('तथ्याङ्क सम्पादक (Editor)', 'editor@insec.org.np', ?, 'editor', TRUE)
      ON DUPLICATE KEY UPDATE 
        name = VALUES(name),
        password_hash = VALUES(password_hash),
        role = VALUES(role),
        is_active = VALUES(is_active);
    `, [adminPasswordHash, editorPasswordHash]);
    console.log('Admin and Editor accounts seeded.');

    // Get Admin & Editor user IDs
    const [users] = await connection.query(`SELECT id, email, role FROM users`);
    const adminUser = users.find(u => u.role === 'admin');
    const editorUser = users.find(u => u.role === 'editor');

    // Step 4: Seed 15 Realistic Records
    const sampleRecords = [
      {
        record_code: 'INSEC-2026-0001',
        form_number: 'FOR-81-01',
        district: 'काठमाडौं',
        municipality: 'काठमाडौं महानगरपालिका',
        ward_number: 14,
        location: 'कुलेश्वर, बल्खु',
        collection_date: '२०८१-०६-१२',
        full_name: 'रामचन्द्र खड्का',
        age: 42,
        gender: 'male',
        family_contact: 'पार्वती खड्का (श्रीमती)',
        phone: '9841234567',
        incident_type: 'death',
        other_incident_type: null,
        incident_date: '२०८१-०६-११',
        incident_location: 'बल्खु खोला किनार',
        incident_description: 'बाढी आएको समयमा खोला किनारबाट सुरक्षित स्थानतर्फ जान खोज्दा बाढीले बगाएर मृत्यु भएको।',
        body_found: 'yes',
        identified: 'yes',
        search_status: 'found',
        family_informed: 'yes',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'verified',
        verified_by: 'इन्सेक केन्द्रीय कार्यालय',
        data_collector: 'सुरेश श्रेष्ठ',
        signature_info: 'डिजिटल हस्ताक्षर प्रमाणीत',
        collection_sign_date: '२०८१-०६-१३',
        created_by: adminUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0002',
        form_number: 'FOR-81-02',
        district: 'ललितपुर',
        municipality: 'गोदावरी नगरपालिका',
        ward_number: 6,
        location: 'टिकाभैरव, लेले',
        collection_date: '२०८१-०६-१२',
        full_name: 'सुनिता तामाङ',
        age: 26,
        gender: 'female',
        family_contact: 'सोम बहादुर तामाङ',
        phone: '9808112233',
        incident_type: 'injured',
        other_incident_type: null,
        incident_date: '२०८१-०६-११',
        incident_location: 'गोदावरी लेले खण्ड',
        incident_description: 'पहिरोमा परी कम्मर र खुट्टामा गम्भीर चोट लागेको, स्थानीयले उद्धार गरेका।',
        body_found: null,
        identified: 'yes',
        search_status: null,
        family_informed: 'yes',
        injury_type: 'खुट्टा र ढाड भाँचिएको (Fracture)',
        treatment_location: 'पाटन अस्पताल, लगनखेल',
        current_condition: 'under_treatment',
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: true,
        is_pregnant: true,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: '७ महिनाको गर्भवती, विशेष उपचार भइरहेको',
        verification_status: 'verified',
        verified_by: 'ललितपुर इन्सेक प्रतिनिधि',
        data_collector: 'अन्जना महर्जन',
        signature_info: 'अन्जना महर्जन',
        collection_sign_date: '२०८१-०६-१३',
        created_by: editorUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0003',
        form_number: 'FOR-81-03',
        district: 'सिन्धुपाल्चोक',
        municipality: 'भोटेकोशी गाउँपालिका',
        ward_number: 4,
        location: 'तातोपानी, डाँडागाउँ',
        collection_date: '२०८१-०६-१३',
        full_name: 'अज्ञात व्यक्ति (पुरुष)',
        age: 35,
        gender: 'male',
        family_contact: 'पहिचान हुन बाँकी',
        phone: null,
        incident_type: 'death',
        other_incident_type: null,
        incident_date: '२०८१-०६-११',
        incident_location: 'भोटेकोशी नदी किनार',
        incident_description: 'नदी किनारमा शव फेला परेको, अनुहार चिन्न नसकिने अवस्थामा रहेकोले सनाखत हुन बाँकी।',
        body_found: 'yes',
        identified: 'no',
        search_status: 'found',
        family_informed: 'no',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'pending',
        verified_by: null,
        data_collector: 'दिपक तामाङ',
        signature_info: 'दिपक तामाङ',
        collection_sign_date: '२०८१-०६-१३',
        created_by: null
      },
      {
        record_code: 'INSEC-2026-0004',
        form_number: 'FOR-81-04',
        district: 'कास्की',
        municipality: 'पोखरा महानगरपालिका',
        ward_number: 19,
        location: 'लामाचौर',
        collection_date: '२०८१-०६-१४',
        full_name: 'आयुष गुरुङ',
        age: 11,
        gender: 'male',
        family_contact: 'धनमाया गुरुङ (हजुरआमा)',
        phone: '9812998877',
        incident_type: 'missing',
        other_incident_type: null,
        incident_date: '२०८१-०६-१२',
        incident_location: 'सेती नदी किनार',
        incident_description: 'विद्यालयबाट घर फर्कने क्रममा बाढी आएको खोल्सा तर्न खोज्दा बेपत्ता भएको, खोजी जारी।',
        body_found: 'no',
        identified: 'yes',
        search_status: 'ongoing',
        family_informed: 'yes',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: true,
        child_guardian_lost: false,
        child_separated_from_family: true,
        child_school_affected: true,
        child_other: 'कक्षा ५ को विद्यार्थी, विद्यालय सामग्री नष्ट',
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'verified',
        verified_by: 'कास्की जिल्ला संयोजक',
        data_collector: 'सरिता बराल',
        signature_info: 'सरिता बराल',
        collection_sign_date: '२०८१-०६-१४',
        created_by: editorUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0005',
        form_number: 'FOR-81-05',
        district: 'कैलाली',
        municipality: 'टीकापुर नगरपालिका',
        ward_number: 8,
        location: 'फाँटा टोल',
        collection_date: '२०८१-०६-१५',
        full_name: 'राधिका चौधरी',
        age: 38,
        gender: 'female',
        family_contact: 'राधिका चौधरी (स्वयं)',
        phone: '9848554433',
        incident_type: 'injured',
        other_incident_type: null,
        incident_date: '२०८१-०६-१२',
        incident_location: 'कर्णाली नदी तटबन्ध',
        incident_description: 'तटबन्ध फुट्दा घर भत्किएर पुरिएकी, टाउको र हातमा चोट।',
        body_found: null,
        identified: 'yes',
        search_status: null,
        family_informed: 'yes',
        injury_type: 'टाउकोमा ५ टाँका लागेको र हात मर्किएको',
        treatment_location: 'टीकापुर अस्पताल',
        current_condition: 'recovered',
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: true,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: true,
        is_woman_led_family: true,
        woman_other: '३ जना बालबच्चाको एकल हेरचाहकर्ता',
        verification_status: 'verified',
        verified_by: 'सुदूरपश्चिम प्रदेश कार्यालय',
        data_collector: 'विनोद चौधरी',
        signature_info: 'विनोद चौधरी',
        collection_sign_date: '२०८१-०६-१५',
        created_by: adminUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0006',
        form_number: 'FOR-81-06',
        district: 'चितवन',
        municipality: 'भरतपुर महानगरपालिका',
        ward_number: 29,
        location: 'सिमलताल, नारायणगढ-मुग्लिन',
        collection_date: '२०८१-०६-१५',
        full_name: 'गोविन्द प्रसाद अधिकारी',
        age: 50,
        gender: 'male',
        family_contact: 'केशव अधिकारी (छोरा)',
        phone: '9855012345',
        incident_type: 'missing',
        other_incident_type: null,
        incident_date: '२०८१-०६-११',
        incident_location: 'त्रिशूली नदी, सिमलताल',
        incident_description: 'पहिरोसँगै बस त्रिशूली नदीमा खस्दा बेपत्ता, सशस्त्र प्रहरी तथा गोताखोर टोलीद्वारा खोजी जारी।',
        body_found: 'no',
        identified: 'yes',
        search_status: 'ongoing',
        family_informed: 'yes',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'verified',
        verified_by: 'इन्सेक बागमती प्रदेश',
        data_collector: 'हरिप्रसाद दवाडी',
        signature_info: 'हरिप्रसाद दवाडी',
        collection_sign_date: '२०८१-०६-१५',
        created_by: editorUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0007',
        form_number: 'FOR-81-07',
        district: 'मोरङ',
        municipality: 'विराटनगर महानगरपालिका',
        ward_number: 12,
        location: 'बखरी',
        collection_date: '२०८१-०६-१६',
        full_name: 'अस्मिता मण्डल',
        age: 7,
        gender: 'female',
        family_contact: 'सन्तोष मण्डल (काका)',
        phone: '9804223344',
        incident_type: 'death',
        other_incident_type: null,
        incident_date: '२०८१-०६-१२',
        incident_location: 'केसलिया खोला किनार',
        incident_description: 'घर डुबानमा परेपछि सुरक्षित स्थानमा सर्ने क्रममा बाढीले बगाएर निधन भएको। आमाबाबु दुबै घाइते।',
        body_found: 'yes',
        identified: 'yes',
        search_status: 'found',
        family_informed: 'yes',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: true,
        child_guardian_lost: true,
        child_separated_from_family: true,
        child_school_affected: true,
        child_other: 'स्थानीय प्राथमिक विद्यालयको छात्रा',
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'verified',
        verified_by: 'इन्सेक कोशी प्रदेश',
        data_collector: 'पवन मण्डल',
        signature_info: 'पवन मण्डल',
        collection_sign_date: '२०८१-०६-१६',
        created_by: adminUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0008',
        form_number: 'FOR-81-08',
        district: 'धनुषा',
        municipality: 'जनकपुरधाम उपमहानगरपालिका',
        ward_number: 8,
        location: 'रेल्वे स्टेशन नजिक',
        collection_date: '२०८१-०६-१६',
        full_name: 'सोनिया खातुन',
        age: 22,
        gender: 'female',
        family_contact: 'मोहमद इद्रिस (पति)',
        phone: '9819001122',
        incident_type: 'injured',
        other_incident_type: null,
        incident_date: '२०८१-०६-१३',
        incident_location: 'जनकपुरधाम वडा नं ८',
        incident_description: 'भारी वर्षाले कच्ची घर भत्किँदा च्यापिएर घाइते, शिशु सहित उद्धार गरिएको।',
        body_found: null,
        identified: 'yes',
        search_status: null,
        family_informed: 'yes',
        injury_type: 'हात र खुट्टामा चोटपटक',
        treatment_location: 'प्रादेशिक अस्पताल जनकपुर',
        current_condition: 'further_treatment_needed',
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: true,
        is_pregnant: false,
        is_postpartum: true,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: '२५ दिनकी सुत्केरी महिला, नवजात शिशुको अवस्था सामान्य',
        verification_status: 'pending',
        verified_by: null,
        data_collector: 'विशाल झा',
        signature_info: 'विशाल झा',
        collection_sign_date: '२०८१-०६-१६',
        created_by: null
      },
      {
        record_code: 'INSEC-2026-0009',
        form_number: 'FOR-81-09',
        district: 'बाँके',
        municipality: 'नेपालगन्ज उपमहानगरपालिका',
        ward_number: 4,
        location: 'बसपार्क',
        collection_date: '२०८१-०६-१७',
        full_name: 'किरण परियार',
        age: 28,
        gender: 'other',
        family_contact: 'आशा परियार',
        phone: '9868112233',
        incident_type: 'other',
        other_incident_type: 'विस्थापन तथा आश्रयविहीन',
        incident_date: '२०८१-०६-१३',
        incident_location: 'डुबान क्षेत्र, नेपालगन्ज',
        incident_description: 'बाढीका कारण बासस्थान पूर्ण रूपमा नष्ट भई सार्वजनिक विद्यालयको अस्थायी शिविरमा आश्रय लिएको।',
        body_found: null,
        identified: 'yes',
        search_status: null,
        family_informed: 'yes',
        injury_type: 'सामान्य चोटपटक',
        treatment_location: 'स्थानीय स्वास्थ्य चौकी',
        current_condition: 'recovered',
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'verified',
        verified_by: 'इन्सेक लुम्बिनी प्रदेश',
        data_collector: 'कमल बिक',
        signature_info: 'कमल बिक',
        collection_sign_date: '२०८१-०६-१७',
        created_by: editorUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0010',
        form_number: 'FOR-81-10',
        district: 'बागलुङ',
        municipality: 'बागलुङ नगरपालिका',
        ward_number: 3,
        location: 'रातामाटा',
        collection_date: '२०8१-०६-१७',
        full_name: 'गणेश बहादुर थापा',
        age: 62,
        gender: 'male',
        family_contact: 'डम्मर थापा (छोरा)',
        phone: '9847123456',
        incident_type: 'death',
        other_incident_type: null,
        incident_date: '२०८१-०६-१२',
        incident_location: 'कालीगण्डकी करिडोर',
        incident_description: 'सडक खुलाउने क्रममा अचानक माथिबाट खसेको ठूलो ढुङ्गाले लागेर घटनास्थलमै निधन।',
        body_found: 'yes',
        identified: 'yes',
        search_status: 'found',
        family_informed: 'yes',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'verified',
        verified_by: 'इन्सेक गण्डकी प्रदेश',
        data_collector: 'सिर्जना शर्मा',
        signature_info: 'सिर्जना शर्मा',
        collection_sign_date: '२०८१-०६-१७',
        created_by: adminUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0011',
        form_number: 'FOR-81-11',
        district: 'जुम्ला',
        municipality: 'चन्दननाथ नगरपालिका',
        ward_number: 5,
        location: 'खलङ्गा बजार',
        collection_date: '२०८१-०६-१८',
        full_name: 'प्रदीप रोकाया',
        age: 16,
        gender: 'male',
        family_contact: 'हर्क रोकाया (बुबा)',
        phone: '9868776655',
        incident_type: 'disabled',
        other_incident_type: null,
        incident_date: '२०८१-०६-१४',
        incident_location: 'तिला नदी पुल नजिक',
        incident_description: 'अज्ञात समूहद्वारा जबर्जस्ती सवारी साधनमा हालेर नियन्त्रणमा लिई लगिएको, प्रहरीमा उजुरी परेको।',
        body_found: null,
        identified: 'yes',
        search_status: 'ongoing',
        family_informed: 'yes',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: true,
        child_guardian_lost: false,
        child_separated_from_family: true,
        child_school_affected: true,
        child_other: 'कक्षा १० का विद्यार्थी',
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'pending',
        verified_by: null,
        data_collector: 'मान बहादुर शाही',
        signature_info: 'मान बहादुर शाही',
        collection_sign_date: '२०८१-०६-१८',
        created_by: editorUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0012',
        form_number: 'FOR-81-12',
        district: 'सिन्धुपाल्चोक',
        municipality: 'मेलम्ची नगरपालिका',
        ward_number: 11,
        location: 'मेलम्ची बजार',
        collection_date: '२०८१-०६-१८',
        full_name: 'माया डङ्गोल',
        age: 45,
        gender: 'female',
        family_contact: 'माया डङ्गोल (स्वयं)',
        phone: '9841887766',
        incident_type: 'injured',
        other_incident_type: null,
        incident_date: '२०८१-०६-११',
        incident_location: 'मेलम्ची पुल नजिक',
        incident_description: 'बाढी पसेपछि पसलबाट सामान निकाल्ने क्रममा पर्खाल भत्किएर खुट्टा थिचिएको।',
        body_found: null,
        identified: 'yes',
        search_status: null,
        family_informed: 'yes',
        injury_type: 'दायाँ खुट्टाको हड्डी फ्र्याक्चर',
        treatment_location: 'धुलिखेल अस्पताल',
        current_condition: 'under_treatment',
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: true,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: true,
        is_woman_led_family: true,
        woman_other: 'एकल महिला, व्यवसाय पूर्ण ध्वस्त',
        verification_status: 'verified',
        verified_by: 'इन्सेक केन्द्रीय अनुसन्धान टोली',
        data_collector: 'सन्तोष नेपाल',
        signature_info: 'सन्तोष नेपाल',
        collection_sign_date: '२०८१-०६-१८',
        created_by: adminUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0013',
        form_number: 'FOR-81-13',
        district: 'काठमाडौं',
        municipality: 'कीर्तिपुर नगरपालिका',
        ward_number: 2,
        location: 'ट्याङ्लाफाँट',
        collection_date: '२०८१-०६-१९',
        full_name: 'अज्ञात व्यक्ति (महिला)',
        age: 30,
        gender: 'female',
        family_contact: 'पहिचान हुन बाँकी',
        phone: null,
        incident_type: 'missing',
        other_incident_type: null,
        incident_date: '२०८१-०६-११',
        incident_location: 'वाग्मती नदी किनार',
        incident_description: 'वाग्मतीमा बगेको प्रत्यक्षदर्शीले बताए पनि शव फेला नपरेको, पहिचान खुल्न नसकेको।',
        body_found: 'no',
        identified: 'no',
        search_status: 'ongoing',
        family_informed: 'no',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: true,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: 'हुलिया: रातो कुर्था, अन्दाजी ३० वर्ष',
        verification_status: 'pending',
        verified_by: null,
        data_collector: 'सविना बज्राचार्य',
        signature_info: 'सविना बज्राचार्य',
        collection_sign_date: '२०८१-०६-१९',
        created_by: null
      },
      {
        record_code: 'INSEC-2026-0014',
        form_number: 'FOR-81-14',
        district: 'झापा',
        municipality: 'भद्रपुर नगरपालिका',
        ward_number: 5,
        location: 'मेची बस्ती',
        collection_date: '२०८१-०६-१९',
        full_name: 'रोशन राजवंशी',
        age: 9,
        gender: 'male',
        family_contact: 'विमल राजवंशी (बुबा)',
        phone: '9824991122',
        incident_type: 'injured',
        other_incident_type: null,
        incident_date: '२०८१-०६-१२',
        incident_location: 'मेची नदी किनार',
        incident_description: 'बाढीले कटान गरेको डिल भत्किँदा खसेर घाइते, स्थानीय युवाहरूले उद्धार गरेका।',
        body_found: null,
        identified: 'yes',
        search_status: null,
        family_informed: 'yes',
        injury_type: 'टाउको र छातीमा चोट',
        treatment_location: 'मेची प्रादेशिक अस्पताल, भद्रपुर',
        current_condition: 'recovered',
        is_child: true,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: true,
        child_other: 'किताब कापी बाढीमा बगेको',
        is_woman: false,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'verified',
        verified_by: 'इन्सेक झापा प्रतिनिधि',
        data_collector: 'दिनेश पोखरेल',
        signature_info: 'दिनेश पोखरेल',
        collection_sign_date: '२०८१-०६-१९',
        created_by: editorUser?.id || null
      },
      {
        record_code: 'INSEC-2026-0015',
        form_number: 'FOR-81-15',
        district: 'काठमाडौं',
        municipality: 'टोखा नगरपालिका',
        ward_number: 2,
        location: 'झोर, बौडेश्वर',
        collection_date: '२०८१-०६-२०',
        full_name: 'कमला सुवेदी',
        age: 34,
        gender: 'female',
        family_contact: 'गोकुल सुवेदी (पति)',
        phone: '9841334455',
        incident_type: 'death',
        other_incident_type: null,
        incident_date: '२०८१-०६-११',
        incident_location: 'झोर महाङ्काल',
        incident_description: 'गोठबाट पशुचौपाया निकाल्ने क्रममा माथिबाट खसेको पहिरोले पुरिएर मृत्यु भएको।',
        body_found: 'yes',
        identified: 'yes',
        search_status: 'found',
        family_informed: 'yes',
        injury_type: null,
        treatment_location: null,
        current_condition: null,
        is_child: false,
        child_guardian_lost: false,
        child_separated_from_family: false,
        child_school_affected: false,
        child_other: null,
        is_woman: true,
        is_pregnant: false,
        is_postpartum: false,
        is_single_woman: false,
        is_woman_led_family: false,
        woman_other: null,
        verification_status: 'verified',
        verified_by: 'इन्सेक बागमती प्रदेश कार्यालय',
        data_collector: 'राजेन्द्र अधिकारी',
        signature_info: 'राजेन्द्र अधिकारी',
        collection_sign_date: '२०८१-०६-२०',
        created_by: adminUser?.id || null
      }
    ];

    console.log(`Inserting ${sampleRecords.length} sample incident records...`);
    for (const record of sampleRecords) {
      await connection.query(`
        INSERT INTO incident_records (
          record_code, form_number, district, municipality, ward_number, location, collection_date,
          full_name, age, gender, family_contact, phone,
          incident_type, other_incident_type, incident_date, incident_location, incident_description,
          body_found, identified, search_status, family_informed,
          injury_type, treatment_location, current_condition,
          is_child, child_guardian_lost, child_separated_from_family, child_school_affected, child_other,
          is_woman, is_pregnant, is_postpartum, is_single_woman, is_woman_led_family, woman_other,
          verification_status, verified_by, data_collector, signature_info, collection_sign_date,
          created_by
        ) VALUES (
          ?, ?, ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?,
          ?, ?, ?, ?,
          ?, ?, ?,
          ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?, ?,
          ?, ?, ?, ?, ?,
          ?
        ) ON DUPLICATE KEY UPDATE
          full_name = VALUES(full_name),
          district = VALUES(district),
          municipality = VALUES(municipality),
          verification_status = VALUES(verification_status);
      `, [
        record.record_code, record.form_number, record.district, record.municipality, record.ward_number, record.location, record.collection_date,
        record.full_name, record.age, record.gender, record.family_contact, record.phone,
        record.incident_type, record.other_incident_type, record.incident_date, record.incident_location, record.incident_description,
        record.body_found, record.identified, record.search_status, record.family_informed,
        record.injury_type, record.treatment_location, record.current_condition,
        record.is_child, record.child_guardian_lost, record.child_separated_from_family, record.child_school_affected, record.child_other,
        record.is_woman, record.is_pregnant, record.is_postpartum, record.is_single_woman, record.is_woman_led_family, record.woman_other,
        record.verification_status, record.verified_by, record.data_collector, record.signature_info, record.collection_sign_date,
        record.created_by
      ]);
    }

    // Insert an initial audit log
    await connection.query(`
      INSERT INTO audit_logs (user_id, user_email, user_role, action, details)
      VALUES (?, 'admin@insec.org.np', 'admin', 'SYSTEM_INIT', ?)
    `, [adminUser?.id || null, JSON.stringify({ message: 'Database initialized with 15 initial incident records and test users.' })]);

    console.log('✅ Database setup completed successfully!');
    console.log('--------------------------------------------------');
    console.log('Starter Accounts:');
    console.log('1. Admin:  admin@insec.org.np  / Admin@12345');
    console.log('2. Editor: editor@insec.org.np / Editor@12345');
    console.log('--------------------------------------------------');
  } catch (error) {
    console.error('❌ Error setting up database:', error);
    process.exit(1);
  } finally {
    await connection.end();
  }
}

setupDatabase();
